### ISSUE TITLE
Uploading an SQL file fails?

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#305]
I'm trying to correct the error in this 'transcription' of 'year'
![screenshot - 22_02_2016 16_45_07](https://cloud.githubusercontent.com/assets/8819910/13244675/5cf35b62-da08-11e5-9b60-c64329467c58.png)

I have what should be the correct SQL file (I've just renamed it .txt to allow upload here, but rename it back to .sql and then try to upload it.
[2016_02_17__Transcriptions_-_Malakula_2_-_West_NCtr_and_Ctr.txt](https://github.com/lingdb/Sound-Comparisons/files/142081/2016_02_17__Transcriptions_-_Malakula_2_-_West_NCtr_and_Ctr.txt)

It says file processed, but I see no change on the website, the problem transcription is still there:
http://www.soundcomparisons.com/#/en/Malakula/map/year/Lgs_Sln

**Comment by runjak** [comment]
There is already an entry in the database for the datum that you want to change:
```
MariaDB [v4]> SELECT * FROM Transcriptions_Malakula
              WHERE LanguageIx = 48742315109
              AND IxElicitation = 51\G
*************************** 1. row ***************************
                            StudyIx: 4
                           FamilyIx: 8
                      IxElicitation: 51
            IxMorphologicalInstance: 0
   AlternativePhoneticRealisationIx: 0
                 AlternativeLexemIx: 0
                         LanguageIx: 48742315109
                           Phonetic: may just be 2 syllables w/o middle V
                      SpellingAltv1: 
                      SpellingAltv2: 
 NotCognateWithMainWordInThisFamily: 0
  CommonRootMorphemeStructDifferent: 0
  DifferentMeaningToUsualForCognate: 0
        ActualMeaningInThisLanguage: 
    OtherLexemeInLanguageForMeaning: 
       RootIsLoanWordFromKnownDonor: 0
          RootSharedInAnotherFamily: 0
                  IsoCodeKnownDonor: 
     DifferentMorphemeStructureNote: 
                       OddPhonology: 0
                   OddPhonologyNote: 
                          UsageNote: 
                       SoundProblem: 0
    ReconstructedOrHistQuestionable: NULL
ReconstructedOrHistQuestionableNote: NULL
                   RecordingMissing: 0
1 row in set (0.00 sec)
```
To change this you need to adjust the `ON DUPLICATE KEY UPDATE` clause of your SQL query,
so that it sets the values accordingly. That means an expression like `Phonetic='nɪsɑːʊ'` would likely need to be added. This is not a bug in either the website or the database but in the query itself.
